"""Context compaction and branch summarization primitives."""

from .branch import (
    BranchPreparation,
    BranchSummaryResult,
    collect_entries_for_branch_summary,
    generate_branch_summary,
    summarize_and_navigate_branch,
)
from .compaction import (
    CompactionCancelled,
    CompactionError,
    collect_file_operations,
    compact,
    compact_session,
    find_cut_point,
    find_turn_start_index,
    prepare_compaction,
    safe_cut_indices,
    serialize_conversation,
    should_compact,
)
from .controller import CompactionController, CompactionDecision
from .token_estimator import (
    IMAGE_ESTIMATE_TOKENS,
    MESSAGE_OVERHEAD_TOKENS,
    calculate_context_tokens,
    estimate_context_tokens,
    estimate_message_tokens,
    estimate_text_tokens,
)
from .types import (
    AfterCompactionHook,
    BeforeCompactionDecision,
    BeforeCompactionHook,
    CompactionPreparation,
    CompactionResult,
    CompactionSettings,
    FileOperations,
    Summarizer,
    SummaryResponse,
    SummaryResult,
)

__all__ = [
    "IMAGE_ESTIMATE_TOKENS",
    "MESSAGE_OVERHEAD_TOKENS",
    "AfterCompactionHook",
    "BeforeCompactionDecision",
    "BeforeCompactionHook",
    "BranchPreparation",
    "BranchSummaryResult",
    "CompactionCancelled",
    "CompactionController",
    "CompactionDecision",
    "CompactionError",
    "CompactionPreparation",
    "CompactionResult",
    "CompactionSettings",
    "FileOperations",
    "Summarizer",
    "SummaryResponse",
    "SummaryResult",
    "calculate_context_tokens",
    "collect_entries_for_branch_summary",
    "collect_file_operations",
    "compact",
    "compact_session",
    "estimate_context_tokens",
    "estimate_message_tokens",
    "estimate_text_tokens",
    "find_cut_point",
    "find_turn_start_index",
    "generate_branch_summary",
    "prepare_compaction",
    "safe_cut_indices",
    "serialize_conversation",
    "should_compact",
    "summarize_and_navigate_branch",
]
