"""Terminal UI primitives and the interactive AgentSession client."""

from .app import (
    InteractiveApp,
    InteractiveAppOptions,
    InteractiveTui,
    TuiOptions,
    run_interactive_mode,
)
from .commands import (
    Command,
    CommandDefinition,
    CommandResult,
    CommandRouter,
    default_commands,
)
from .completion import (
    CommandCompleter,
    Completer,
    Completion,
    CompletionItem,
    CompletionRequest,
    CompositeCompleter,
    FileCompleter,
    ModelCompleter,
    apply_completion,
)
from .components import (
    CompletionOverlay,
    Component,
    MessageComponent,
    Spacer,
    TextBlock,
    ToolProgressComponent,
    VBox,
)
from .components import StatusBar as ComponentStatusBar
from .editor import EditorAction, EditorRender, TextEditor
from .images import (
    TerminalImage,
    encode_iterm_image,
    encode_kitty_image,
    fit_terminal_cells,
    render_terminal_image,
    terminal_image_from_bytes,
)
from .input import InputDecoder, InputParser
from .markdown import render_markdown
from .screen import (
    SYNC_BEGIN,
    SYNC_END,
    AnsiRenderer,
    Canvas,
    ScreenRenderer,
    Viewport,
)
from .surface import Surface, SurfaceDiff
from .terminal import (
    KeyDecoder,
    MemoryTerminal,
    OutputBuffer,
    StdioTerminal,
    Terminal,
    TerminalCapabilities,
    detect_terminal_capabilities,
    events,
)
from .types import (
    Cell,
    Color,
    Cursor,
    EndOfInputEvent,
    Frame,
    KeyEvent,
    MouseEvent,
    PasteEvent,
    Point,
    Rect,
    ResizeEvent,
    Size,
    Style,
    StyledText,
    TerminalEvent,
    TextStyle,
    TickEvent,
    cell_width,
    grapheme_width,
    graphemes,
    pad_cells,
    slice_cells,
    strip_ansi,
    text_width,
    truncate_cells,
    truncate_text,
    wrap_cells,
)
from .view import CompletionView, StatusView, TranscriptView, View
from .widgets import (
    SelectList,
    SelectOption,
    StatusBar,
    TranscriptItem,
)
from .widgets import TranscriptView as SurfaceTranscriptView

__all__ = [
    "SYNC_BEGIN",
    "SYNC_END",
    "AnsiRenderer",
    "Canvas",
    "Cell",
    "Color",
    "Command",
    "CommandCompleter",
    "CommandDefinition",
    "CommandResult",
    "CommandRouter",
    "Completer",
    "Completion",
    "CompletionItem",
    "CompletionOverlay",
    "CompletionRequest",
    "CompletionView",
    "Component",
    "ComponentStatusBar",
    "CompositeCompleter",
    "Cursor",
    "EditorAction",
    "EditorRender",
    "EndOfInputEvent",
    "FileCompleter",
    "Frame",
    "InputDecoder",
    "InputParser",
    "InteractiveApp",
    "InteractiveAppOptions",
    "InteractiveTui",
    "KeyDecoder",
    "KeyEvent",
    "MemoryTerminal",
    "MessageComponent",
    "ModelCompleter",
    "MouseEvent",
    "OutputBuffer",
    "PasteEvent",
    "Point",
    "Rect",
    "ResizeEvent",
    "ScreenRenderer",
    "SelectList",
    "SelectOption",
    "Size",
    "Spacer",
    "StatusBar",
    "StatusView",
    "StdioTerminal",
    "Style",
    "StyledText",
    "Surface",
    "SurfaceDiff",
    "SurfaceTranscriptView",
    "Terminal",
    "TerminalCapabilities",
    "TerminalEvent",
    "TerminalImage",
    "TextBlock",
    "TextEditor",
    "TextStyle",
    "TickEvent",
    "ToolProgressComponent",
    "TranscriptItem",
    "TranscriptView",
    "TuiOptions",
    "VBox",
    "View",
    "Viewport",
    "apply_completion",
    "cell_width",
    "default_commands",
    "detect_terminal_capabilities",
    "encode_iterm_image",
    "encode_kitty_image",
    "events",
    "fit_terminal_cells",
    "grapheme_width",
    "graphemes",
    "pad_cells",
    "render_markdown",
    "render_terminal_image",
    "run_interactive_mode",
    "slice_cells",
    "strip_ansi",
    "terminal_image_from_bytes",
    "text_width",
    "truncate_cells",
    "truncate_text",
    "wrap_cells",
]
