"""Provider-neutral AI contracts and streaming adapters."""

from .cancellation import CancellationToken
from .errors import ProviderErrorDetails, ProviderRequestError
from .event_stream import AssistantMessageEventStream, EventStream
from .events import (
    AssistantMessageEvent,
    DoneEvent,
    ErrorEvent,
    StartEvent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
)
from .faux import FauxProvider
from .json_parse import parse_streaming_json
from .openai_compatible import (
    AsyncLineTransport,
    HttpStreamRequest,
    OpenAICompatibleProvider,
    UrllibLineTransport,
)
from .provider import Provider, StreamFunction, provider_stream
from .registry import ModelRegistry, ProviderRegistry
from .types import (
    AssistantMessage,
    Context,
    ImageContent,
    Message,
    Model,
    ModelCost,
    ModelCostTier,
    ProviderResponse,
    StreamOptions,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolDefinition,
    ToolResultMessage,
    Usage,
    UsageCost,
    UserMessage,
    message_from_dict,
    message_text,
    message_to_dict,
)

__all__ = [
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "AsyncLineTransport",
    "CancellationToken",
    "Context",
    "DoneEvent",
    "ErrorEvent",
    "EventStream",
    "FauxProvider",
    "HttpStreamRequest",
    "ImageContent",
    "Message",
    "Model",
    "ModelCost",
    "ModelCostTier",
    "ModelRegistry",
    "OpenAICompatibleProvider",
    "Provider",
    "ProviderErrorDetails",
    "ProviderRegistry",
    "ProviderRequestError",
    "ProviderResponse",
    "StartEvent",
    "StreamFunction",
    "StreamOptions",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingStartEvent",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolDefinition",
    "ToolResultMessage",
    "UrllibLineTransport",
    "Usage",
    "UsageCost",
    "UserMessage",
    "message_from_dict",
    "message_text",
    "message_to_dict",
    "parse_streaming_json",
    "provider_stream",
]
