"""Harness primitives for execution, tools, sessions, compaction, and resources."""

from .compaction import (
    CompactionController,
    CompactionSettings,
    SummaryResult,
    compact,
    prepare_compaction,
)
from .environment import (
    LocalExecutionEnv,
    LocalFileSystem,
    LocalShell,
    create_local_execution_env,
)
from .harness import AgentHarness
from .image import detect_supported_image_mime_type, encode_base64
from .path_utils import normalize_tool_path, resolve_read_tool_path, resolve_tool_path
from .resource_loader import ResourceLoader, ResourceLoaderConfig, parse_frontmatter
from .resource_types import (
    ContextFile,
    ExtensionResource,
    PackageResource,
    PromptTemplate,
    ResourceSnapshot,
    ResourceSource,
    ResourceWarning,
    Skill,
    Theme,
)
from .result import (
    Err,
    HarnessResult,
    Ok,
    Result,
    build_harness_result,
    err,
    get_or_raise,
    get_or_throw,
    get_or_undefined,
    ok,
    to_error,
)
from .session import SessionManager
from .system_prompt import SystemPromptBuilder, SystemPromptSections, render_prompt_template
from .tools import (
    create_bash_tool,
    create_coding_tools,
    create_edit_tool,
    create_read_tool,
    create_write_tool,
)
from .truncate import (
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_LINES,
    GREP_MAX_LINE_LENGTH,
    TruncatedText,
    TruncationResult,
    format_size,
    truncate_head,
    truncate_line,
    truncate_tail,
    truncate_text,
)
from .types import (
    BranchSummaryError,
    CompactionError,
    ExecutionEnv,
    ExecutionError,
    FileError,
    FileInfo,
    FileSystem,
    Shell,
    ShellExecOptions,
    ShellResult,
)

__all__ = [
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_LINES",
    "GREP_MAX_LINE_LENGTH",
    "AgentHarness",
    "BranchSummaryError",
    "CompactionController",
    "CompactionError",
    "CompactionSettings",
    "ContextFile",
    "Err",
    "ExecutionEnv",
    "ExecutionError",
    "ExtensionResource",
    "FileError",
    "FileInfo",
    "FileSystem",
    "HarnessResult",
    "LocalExecutionEnv",
    "LocalFileSystem",
    "LocalShell",
    "Ok",
    "PackageResource",
    "PromptTemplate",
    "ResourceLoader",
    "ResourceLoaderConfig",
    "ResourceSnapshot",
    "ResourceSource",
    "ResourceWarning",
    "Result",
    "SessionManager",
    "Shell",
    "ShellExecOptions",
    "ShellResult",
    "Skill",
    "SummaryResult",
    "SystemPromptBuilder",
    "SystemPromptSections",
    "Theme",
    "TruncatedText",
    "TruncationResult",
    "build_harness_result",
    "compact",
    "create_bash_tool",
    "create_coding_tools",
    "create_edit_tool",
    "create_local_execution_env",
    "create_read_tool",
    "create_write_tool",
    "detect_supported_image_mime_type",
    "encode_base64",
    "err",
    "format_size",
    "get_or_raise",
    "get_or_throw",
    "get_or_undefined",
    "normalize_tool_path",
    "ok",
    "parse_frontmatter",
    "prepare_compaction",
    "render_prompt_template",
    "resolve_read_tool_path",
    "resolve_tool_path",
    "to_error",
    "truncate_head",
    "truncate_line",
    "truncate_tail",
    "truncate_text",
]
